### ISSUE TITLE
where is the model?

### ISSUE THREAD

**Issue by scybd** [fdcl-gwu/gazebo_uav_control#2]
It seems that this project doesn't have a uav's urdf file.

**Comment by kanishkegb** [comment]
Are you using this on a computer without internet? Gazebo downloads the models from [here](https://github.com/osrf/gazebo_models) automatically.

**Comment by kanishkegb** [comment]
Did it fix your issue? Is #1 related to this too?

**Comment by scybd** [comment]
- ![image](https://github.com/fdcl-gwu/gazebo_uav_control/assets/105584894/b8731b67-42b2-426c-8532-d7b1a2195ea1)
- Yes, the problems I encountered were all because my network was not good. I chose to download the [quadrotor model](https://app.gazebosim.org/OpenRobotics/fuel/models/Quadrotor) and load it locally, finally it ran well. Thank you very much for your help!
